// <auto-generated />
using System;
using Backend.DataContext;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Backend.Migrations
{
    [DbContext(typeof(AgoraContext))]
    partial class AgoraContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.19")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("Service.Models.Capacitacion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Cupo")
                        .HasColumnType("int");

                    b.Property<string>("Detalle")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("FechaHora")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("InscripcionAbierta")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Ponente")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Capacitaciones");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Cupo = 30,
                            Detalle = "Aprende los conceptos básicos de programación.",
                            FechaHora = new DateTime(2025, 8, 29, 18, 34, 10, 925, DateTimeKind.Local).AddTicks(4901),
                            InscripcionAbierta = true,
                            IsDeleted = false,
                            Nombre = "Introducción a la Programación",
                            Ponente = "Carlos Gómez"
                        },
                        new
                        {
                            Id = 2,
                            Cupo = 25,
                            Detalle = "Crea aplicaciones web modernas con ASP.NET Core.",
                            FechaHora = new DateTime(2025, 9, 8, 18, 34, 10, 925, DateTimeKind.Local).AddTicks(4960),
                            InscripcionAbierta = true,
                            IsDeleted = false,
                            Nombre = "Desarrollo Web con ASP.NET Core",
                            Ponente = "Ana Martínez"
                        });
                });

            modelBuilder.Entity("Service.Models.Inscripcion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Acreditado")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Apellido")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("CapacitacionId")
                        .HasColumnType("int");

                    b.Property<string>("Dni")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<decimal>("Importe")
                        .HasColumnType("decimal(65,30)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<bool>("Pagado")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("TipoInscripcionId")
                        .HasColumnType("int");

                    b.Property<int?>("UsuarioCobroId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CapacitacionId");

                    b.HasIndex("TipoInscripcionId");

                    b.HasIndex("UsuarioCobroId");

                    b.ToTable("Inscripciones");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Acreditado = false,
                            Apellido = "Pérez",
                            CapacitacionId = 1,
                            Dni = "12345678",
                            Email = "perezjuan@gmail.com",
                            Importe = 10000m,
                            IsDeleted = false,
                            Nombre = "Juan",
                            Pagado = false,
                            TipoInscripcionId = 1
                        },
                        new
                        {
                            Id = 2,
                            Acreditado = false,
                            Apellido = "Gómez",
                            CapacitacionId = 2,
                            Dni = "87654321",
                            Email = "gomezana@gmail.com",
                            Importe = 8000m,
                            IsDeleted = false,
                            Nombre = "Ana",
                            Pagado = false,
                            TipoInscripcionId = 2
                        },
                        new
                        {
                            Id = 3,
                            Acreditado = false,
                            Apellido = "Lopez",
                            CapacitacionId = 1,
                            Dni = "12345678",
                            Email = "lopezmaria@gmail.com",
                            Importe = 5000m,
                            IsDeleted = false,
                            Nombre = "Maria",
                            Pagado = false,
                            TipoInscripcionId = 3
                        });
                });

            modelBuilder.Entity("Service.Models.TipoInscripcion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("TipoInscripciones");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            IsDeleted = false,
                            Nombre = "Público en general"
                        },
                        new
                        {
                            Id = 2,
                            IsDeleted = false,
                            Nombre = "Docentes"
                        },
                        new
                        {
                            Id = 3,
                            IsDeleted = false,
                            Nombre = "Estudiantes"
                        },
                        new
                        {
                            Id = 4,
                            IsDeleted = false,
                            Nombre = "Jubilados"
                        });
                });

            modelBuilder.Entity("Service.Models.TipoInscripcionCapacitacion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CapacitacionId")
                        .HasColumnType("int");

                    b.Property<decimal>("Costo")
                        .HasColumnType("decimal(65,30)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("TipoInscripcionId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CapacitacionId");

                    b.HasIndex("TipoInscripcionId");

                    b.ToTable("TiposInscripcionesCapacitaciones");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CapacitacionId = 1,
                            Costo = 10000m,
                            IsDeleted = false,
                            TipoInscripcionId = 1
                        },
                        new
                        {
                            Id = 2,
                            CapacitacionId = 1,
                            Costo = 8000m,
                            IsDeleted = false,
                            TipoInscripcionId = 2
                        },
                        new
                        {
                            Id = 3,
                            CapacitacionId = 2,
                            Costo = 5000m,
                            IsDeleted = false,
                            TipoInscripcionId = 3
                        },
                        new
                        {
                            Id = 4,
                            CapacitacionId = 2,
                            Costo = 3000m,
                            IsDeleted = false,
                            TipoInscripcionId = 4
                        });
                });

            modelBuilder.Entity("Service.Models.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DeleteDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("TipoUsuario")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Usuarios");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DeleteDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "admin@gmail.com",
                            IsDeleted = false,
                            Nombre = "Administrador",
                            Password = "admin123",
                            TipoUsuario = 2
                        },
                        new
                        {
                            Id = 2,
                            DeleteDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "",
                            IsDeleted = false,
                            Nombre = "Usuario",
                            Password = "user123",
                            TipoUsuario = 0
                        });
                });

            modelBuilder.Entity("Service.Models.Inscripcion", b =>
                {
                    b.HasOne("Service.Models.Capacitacion", "Capacitacion")
                        .WithMany()
                        .HasForeignKey("CapacitacionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Service.Models.TipoInscripcion", "TipoInscripcion")
                        .WithMany()
                        .HasForeignKey("TipoInscripcionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Service.Models.Usuario", "UsuarioCobro")
                        .WithMany()
                        .HasForeignKey("UsuarioCobroId");

                    b.Navigation("Capacitacion");

                    b.Navigation("TipoInscripcion");

                    b.Navigation("UsuarioCobro");
                });

            modelBuilder.Entity("Service.Models.TipoInscripcionCapacitacion", b =>
                {
                    b.HasOne("Service.Models.Capacitacion", "Capacitacion")
                        .WithMany()
                        .HasForeignKey("CapacitacionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Service.Models.TipoInscripcion", "TipoInscripcion")
                        .WithMany()
                        .HasForeignKey("TipoInscripcionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Capacitacion");

                    b.Navigation("TipoInscripcion");
                });
#pragma warning restore 612, 618
        }
    }
}
